# Generated by Django 5.2.4 on 2025-08-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(auto_created=True)),
                ('fname', models.CharField(max_length=244)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=244)),
                ('expense_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('NEED', 'Need'), ('LUXURY', 'Luxury'), ('INVESTMENT', 'Investment')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
    ]
